version: '3.1'
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynet
  giropops:
    image: linuxtips-giropops-senhas:1.0
    container_name: giropops
    build:
      context: .
      dockerfile: dockerfile
      args:
        - REDIS_HOST=redis
    ports:
      - "5000:5000"
    networks:
      - mynet
    depends_on:
      - redis
networks:
  mynet:
    driver: bridge