version: '3.1'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - mynet
  giropops:
    image: linuxtips-giropops-senhas:1.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REDIS_HOST=redis
      tags:
        - "latest"
        - "1.0"
    ports:
      - "5000:5000"
    networks:
      - mynet
    depends_on:
      - redis
networks:
  mynet:
    driver: bridge